title: 'Lo menos importante'
default_lang: es
author:
  name: 'Gabo Lato'
  email: hola@latorregabriel.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Hablamos de cosas que quizás no te interesen.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
